| <img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Python_logo_and_wordmark.svg" style="height:100px"> | <img src="https://upload.wikimedia.org/wikipedia/commons/e/ed/Pandas_logo.svg" style="height:150px"> |
| --- | --- |



# PANDAS - Data Frame | Data Categorization

In [2]:
import pandas as pd

In [3]:
file = "daily_weather_data.csv"

df = pd.read_csv(file)

df

,date,country,city,Latitude,Longitude,tavg,tmin,tmax,wdir,wspd,pres
0,21-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,23.4,20.9,25.5,329.0,9.3,1009.6
1,22-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,23.5,21.0,25.7,337.0,9.4,1010.0
2,23-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,23.5,21.1,25.5,41.0,8.2,1007.7
3,24-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,24.3,20.8,27.1,10.0,9.3,1004.4
4,25-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,26.5,22.7,30.0,9.0,9.7,1002.0
...,...,...,...,...,...,...,...,...,...,...,...
324642,07-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,22.1,18.6,25.6,3.0,24.7,1013.7
324643,08-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,22.1,19.6,25.6,2.0,20.5,1013.0
324644,09-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,23.4,19.6,29.6,34.0,24.0,1015.4
324645,10-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,23.1,18.6,29.7,39.0,28.4,1017.6
324646,11-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,21.4,17.3,27.5,21.0,21.3,1018.6

## 1. Metode 1

Pengkategorian data dapat menggunakan beberapa metode. Metode yang pertama adalah dengan membuat tambahan kolom untuk kategori data. Setelah itu, setiap value akan dikelompokkan sesuai dengan kategorisasi yang dibuat.

Klasifikasi angin berdasarkan kecepatan menurut Beaufort :

|Angin||Kecepatan (km/jam)||Klasifikasi||Fenomena|
|:---:||:---:||:---:||:---:|
|0||<1.6||Calm||Asap bergerak vertikal|
|1||1.6 - 4.8||Light Air||Arah angin ditunjukkan oleh asap|
|2||6.4 - 11.3||Light Breeze||Terasa pada muka, daun berisik, penunjuk angin mulai bergerak|
|3||12.9 - 19.3||Gentle Breeze||Daun dan ranting bergerak tetap, bendera berkibar|
|4||20.9 - 29.0||Moderate Breeze||Menggerakkan tangkai kecil, menghembus debu dan kertas|
|5||30.6 - 38.6||Fresh Breeze||Pohon kecil yang berdaun mulai bergoyang|
|6||40.2 - 49.9||Strong Breeze||Dahan besar begoyang, kawat telpon berdering|
|7||51.5 - 61.1||Moderate Gale||Seluruh pohon bergoyang|
|8||62.8 - 74.0||Fresh Gale||Ranting pohon patah|
|9||75.6 - 86.9||Strong Gale||Bangunan ringan rusak|
|10||88.5 - 101.4||Whole Gale||Bangunan rusak, pohon tumbang|
|11||103.0 - 120.7||Storm||Kerusakan bangunan sangat banyak|
|12||>120.7||Hurricane||Kerusakan besar, dahsyat dan meluas|

In [4]:
df

,date,country,city,Latitude,Longitude,tavg,tmin,tmax,wdir,wspd,pres
0,21-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,23.4,20.9,25.5,329.0,9.3,1009.6
1,22-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,23.5,21.0,25.7,337.0,9.4,1010.0
2,23-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,23.5,21.1,25.5,41.0,8.2,1007.7
3,24-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,24.3,20.8,27.1,10.0,9.3,1004.4
4,25-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,26.5,22.7,30.0,9.0,9.7,1002.0
...,...,...,...,...,...,...,...,...,...,...,...
324642,07-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,22.1,18.6,25.6,3.0,24.7,1013.7
324643,08-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,22.1,19.6,25.6,2.0,20.5,1013.0
324644,09-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,23.4,19.6,29.6,34.0,24.0,1015.4
324645,10-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,23.1,18.6,29.7,39.0,28.4,1017.6
324646,11-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,21.4,17.3,27.5,21.0,21.3,1018.6

In [6]:
# 1. Buatlah kolom tambahan untuk meletakkan kategorisasi data yang diisi oleh value yang belum ditentukan


df['category'] ='undefined'

df

,date,country,city,Latitude,Longitude,tavg,tmin,tmax,wdir,wspd,pres,category
0,21-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,23.4,20.9,25.5,329.0,9.3,1009.6,undefined
1,22-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,23.5,21.0,25.7,337.0,9.4,1010.0,undefined
2,23-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,23.5,21.1,25.5,41.0,8.2,1007.7,undefined
3,24-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,24.3,20.8,27.1,10.0,9.3,1004.4,undefined
4,25-07-2018,Abkhazia,Sukhumi,43.001525,41.023415,26.5,22.7,30.0,9.0,9.7,1002.0,undefined
...,...,...,...,...,...,...,...,...,...,...,...,...
324642,07-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,22.1,18.6,25.6,3.0,24.7,1013.7,undefined
324643,08-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,22.1,19.6,25.6,2.0,20.5,1013.0,undefined
324644,09-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,23.4,19.6,29.6,34.0,24.0,1015.4,undefined
324645,10-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,23.1,18.6,29.7,39.0,28.4,1017.6,undefined
324646,11-10-2022,Western Sahara,El Aaiún,27.125287,-13.162500,21.4,17.3,27.5,21.0,21.3,1018.6,undefined

In [13]:
# 2. Setelah kolom kategori tersebut dibuat, maka data harus dikelompokkan sesuai yang diinginkan satu persatu pada kolom "category"

df.loc[df['wspd'] <1.6, 'category' ] = 'Calm'

df[df['category'] == 'Calm']

,date,country,city,Latitude,Longitude,tavg,tmin,tmax,wdir,wspd,pres,category
1562,19-01-2018,Aland Islands,Mariehamn,60.100000,19.933333,-5.6,-10.9,-1.8,9.0,1.3,1003.3,Calm
1836,20-10-2018,Aland Islands,Mariehamn,60.100000,19.933333,3.6,-0.4,9.6,348.0,1.4,1021.0,Calm
10511,01-10-2018,Anguilla,The Valley,18.214813,-63.057441,28.3,26.6,31.6,95.0,1.4,1013.7,Calm
10512,02-10-2018,Anguilla,The Valley,18.214813,-63.057441,28.1,25.6,31.2,100.0,1.3,1012.8,Calm
24405,27-07-2018,Bangladesh,Dhaka,23.810332,90.412518,28.1,25.9,30.1,NaN,1.2,999.4,Calm
...,...,...,...,...,...,...,...,...,...,...,...,...
305738,14-10-2018,Ukraine,Kiev,50.450100,30.523400,9.4,1.6,20.3,NaN,1.5,1031.5,Calm
312987,10-07-2019,Uruguay,Montevideo,-34.901113,-56.164531,12.9,10.8,15.8,48.0,1.2,1017.7,Calm
312993,16-07-2019,Uruguay,Montevideo,-34.901113,-56.164531,6.1,0.8,13.8,20.0,1.0,1024.6,Calm
315628,22-12-2021,Vanuatu,Port Vila,-17.733251,168.327325,26.0,21.9,31.2,5.0,1.5,1008.3,Calm
315629,23-12-2021,Vanuatu,Port Vila,-17.733251,168.327325,25.4,22.5,31.3,358.0,1.4,1008.2,Calm

In [43]:
df.loc[df['wspd'] >1.6 and  4.8, 'category' ] = 'Light Air'

df[df['category'] == 'Light Air']

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().